version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: myapp
    ports:
      - 8080:8080
    depends_on:
      - mongodb